#
%
*
+
-
->
->>
-?>
-?>>
.
..
/
//
:
<
<=
=
>
>=
^
and|comment|do|doc|doto|each|
eval-compiler|
fn|for|global|hashfn|if|include|lambda
length|let|local|lua|macro|macros|match|not
not=|
or|partial|quote|
require-macros|
set
set-forcibly!|tset|values|var|when|while
~=
λ

and|comment|do|doc|doto|each|eval-compiler|fn|for|global|hashfn|if|include|lambda|length|let|local|lua|macro|macros|match|not|not=|or|partial|quote|require-macros|set|set-forcibly!|tset|values|var|when|while